### ISSUE TITLE
The demo of the EthSigner is incomplete

### ISSUE THREAD

**Issue by wuyingfengsui** [seanjameshan/starknet.js#999]
I found the `EthSigner` in [the document](https://www.starknetjs.com/docs/next/guides/connect_account#connect-to-an-account-that-uses-ethereum-signature). I think it can be used when I already have an ETH account. But I can't find how to generate a starknet address from eth private key.

**Comment by PhilippeR26** [comment]
Hello,
You are right. That's why the PR https://github.com/starknet-io/starknet.js/pull/985 has been proposed, to have a full compatibility with the new OpenZeppelin Ethereum account.
This PR is waiting a review from the team, but it's not priority one.
Once merged, you will be able to have the account address this way : https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/da4431bf8b250d2503b008d0a7a997cda5923e95/src/scripts/15.createNewETHaccount.ts#L62

**Comment by PhilippeR26** [comment]
Do you mean the code in my tuto?

**Comment by PhilippeR26** [comment]
This commit is rather old.
Please checkout latest commit and re-test.
